---
calico_image: calico/node
calico_image_tag: v0.9.0

bintray_baseurl: "https://bintray.com/artifact/download/asteris"
calico_binary: "{{ bintray_baseurl }}/calico/calicoctl/calicoctl"

etcd_service_name: etcd.service.{{ consul_dns_domain }}
etcd_client_port: 2379

calico_etcdaddr: "{{ private_ipv4 }}:{{ etcd_client_port }}"

calico_network: 192.168.0.0/16

calico_profile: dev
