---
# Gluster distributed storage. Run this playbook after running the core playbook
# (terraform.sample.yml)

# CHECK SECURITY - when customizing you should leave this in. If you take it out
# and forget to specify security.yml, security could be turned off on components
# in your cluster!
- hosts: localhost
  gather_facts: no
  tasks:
    - name: check for security
      when: security_enabled is not defined or not security_enabled
      fail:
        msg: |
          Security is not enabled. Please run `security-setup` in the root
          directory and re-run this playbook with the `--extra-vars`/`-e` option
          pointing to your `security.yml` (e.g., `-e @security.yml`)

- hosts: role=control
  vars:
    consul_dns_domain: consul
    glusterfs_mode: server
  roles:
    - glusterfs

- hosts: role=worker
  gather_facts: no
  vars:
    consul_dns_domain: consul
    glusterfs_mode: client
  roles:
    - glusterfs