
# dependency for cloud-utils-growpart
# which is required if we have GROWPART=yes (default) in /etc/sysconfig/docker-storage-setup
- name: install cloud-utils-growpart package
  sudo: yes
  yum:
    name: "cloud-utils-growpart"
    state: present
  tags:
    - docker
    - bootstrap

- name: install docker-storage-setup config
  sudo: yes
  template:
    src: docker-storage-setup.conf.j2
    dest: /etc/sysconfig/docker-storage-setup
  tags:
    - docker
